### ISSUE TITLE
write down all backend APIs here

### ISSUE THREAD

**Issue by daywednes** [codelight-co/runebeta#1]

**Comment by mison201** [comment]
## User profile
- [ ] GET - User profile
- [ ] POST - Login
- [ ] POST - Logout

## Home page
- [ ] GET - Block height
- [ ] GET - Daily transaction count
- [ ] GET - List transaction
- [ ] GET - Protocol Stats (Total Rune Etched, Total Rune Transaction, Total Fee, Daily Transaction)
- [ ] GET - Block sync number
- [ ] GET - Btc price
- [ ] GET - Search All (Transation id, rune id, block number...)

## Transaction detail page
- [ ] GET - Transaction by id

## Address detail page
- [ ] GET - List transaction by address
- [ ] GET - List the rune owner by their address ID

## List rune page
- [ ] GET - List rune

## Rune detail page
- [ ] GET - Rune info by id
- [ ] GET - Top rune holder
- [ ] GET - List transaction by rune id

## ETCH / Transfer page
- [ ] POST - Transfer to address

## Market page
- [ ] GET - Martket Stats
- [ ] GET - List rune on market

## Rune order page
- [ ] GET - List market order by rune id
- [ ] GET - My UTXO
- [ ] GET - Available balance for sale
- [ ] POST - Buy rune order

**Comment by daywednes** [comment]
## User profile
- [ ] GET - User profile - P2
- [ ] POST - Login - P2
- [ ] POST - Logout - P2

## Home page
- [ ] GET - Block height - we can get from indexer
- [ ] GET - Daily transaction count - we can get from indexer
- [ ] GET - List transaction - we can get from indexer
- [ ] GET - Protocol Stats (Total Rune Etched, Total Rune Transaction, Total Fee, Daily Transaction)
- [ ] GET - Block sync number - we can get from indexer
- [ ] GET - Btc price 
- [ ] GET - Search All (Transation id, rune id, block number...) - all data should be stored in redis ( 3 different things but they ca not be overlapped). all data we got from indexer can be populated into the redis database.

## Transaction detail page
- [ ] GET - Transaction by id -- indexer

## Address detail page
- [ ] GET - List transaction by address
- [ ] GET - List the rune owner by their address ID

## List rune page
- [ ] GET - List rune

## Rune detail page
- [ ] GET - Rune info by id
- [ ] GET - Top rune holder
- [ ] GET - List transaction by rune id

## ETCH / Transfer page
- [ ] POST - Transfer to address

## Market page
- [ ] GET - Martket Stats
- [ ] GET - List rune on market

## Rune order page
- [ ] GET - List market order by rune id
- [ ] GET - My UTXO
- [ ] GET - Available balance for sale
- [ ] POST - Buy rune order

**Comment by daywednes** [comment]
@mison201 assuming we got all APIs - let's work on the estimations (just backend only)

**Comment by vuviettai** [comment]
-[ ] GET - List transaction
 -[ ] GET - Protocol Stats (Total Rune Etched, Total Rune Transaction, Total Fee, Daily Transaction)

Data for these apis stored by indexer in redb, are not friendly for query. So we need modify indexing code for writing data into postgres
